# SPDX-License-Identifier: GPL-2.0
#
# Makefile for non-discoverable daughterboards
#
obj-$(CONFIG_96BOARDS_LS_CONNECTOR)	+= 96boards-ls-bus.o 96boards-ls-connector.o
obj-$(CONFIG_96BOARDS_SECURE96)		+= 96boards-secure96.o
