// SPDX-License-Identifier: GPL-2.0
#ifndef _DT_BINDINGS_CLK_MSM_MMCC_8660_H
#define _DT_BINDINGS_CLK_MSM_MMCC_8660_H

#define GMEM_AXI_CLK		0
#define IJPEG_AXI_CLK		1
#define IMEM_AXI_CLK		2
#define JPEGD_AXI_CLK		3
#define MDP_AXI_CLK		4
#define VCODEC_AXI_CLK		5
#define VFE_AXI_CLK		6
#define ROT_AXI_CLK		7
#define VPE_AXI_CLK		8
#define SMI_2X_AXI_CLK		9
#define AMP_AHB_CLK		10
#define CSI0_AHB_CLK		11
#define CSI1_AHB_CLK		12
#define DSI_M_AHB_CLK		13
#define DSI_S_AHB_CLK		14
#define GFX2D0_AHB_CLK		15
#define GFX2D1_AHB_CLK		16
#define GFX3D_AHB_CLK		17
#define HDMI_M_AHB_CLK		18
#define HDMI_S_AHB_CLK		19
#define IJPEG_AHB_CLK		20
#define IMEM_AHB_CLK		21
#define JPEGD_AHB_CLK		22
#define MDP_AHB_CLK		23
#define ROT_AHB_CLK		24
#define SMMU_AHB_CLK		25
#define TV_ENC_AHB_CLK		26
#define VCODEC_AHB_CLK		27
#define VFE_AHB_CLK		28
#define VPE_AHB_CLK		29
#define GFX3D_SRC		30
#define GFX3D_CLK		31
#define MDP_SRC			32
#define MDP_CLK			33
#define MDP_VSYNC_SRC		34
#define MDP_VSYNC_CLK		35
#define MDP_PIXEL_SRC		36
#define MDP_PIXEL_CLK		37
#define MDP_LCDC_CLK		38
#define ROT_SRC			39
#define ROT_CLK			40
#define CAM_SRC			41
#define CAM_CLK			42
#define CSI_SRC			43
#define CSI0_CLK		44
#define CSI1_CLK		45
#define DSI_BYTE_SRC		46
#define DSI_BYTE_CLK		47
#define DSI_ESC_CLK		48
#define TV_SRC			49
#define TV_ENC_CLK		50
#define TV_DAC_CLK		51
#define MDP_TV_CLK		52
#define HDMI_TV_CLK		53
#define HDMI_APP_CLK		54
#define VCODEC_SRC		55
#define VCODEC_CLK		56
#define VPE_SRC			57
#define VPE_CLK			58
#define VFE_SRC			59
#define VFE_CLK			60
#define CSI0_VFE_CLK		61
#define CSI1_VFE_CLK		62
#define PLL2			63
#define PLL3			64

#endif
