# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_DT_EASY50712)	+= danube_easy50712.dtb
dtb-$(CONFIG_DT_ZYXEL_P_2812HNU_F1)	+= vr9_zyxel_p-2812hnu-f1.dtb
dtb-$(CONFIG_DT_ZYXEL_P_2812HNU_F3)	+= vr9_zyxel_p-2812hnu-f3.dtb

obj-$(CONFIG_BUILTIN_DTB)	+= $(addsuffix .o, $(dtb-y))
